name: 'Update README with Badges'
description: 'A GitHub Action to update the README.md with badges'
author: 'Jeffrey Patton'

inputs:
  project_name:
    description: 'The project name'
    required: true
  github_owner:
    description: 'GitHub repository owner'
    required: false
    default: ${{ github.repository_owner }}  # Set the default to the current repo owner
  github_repo:
    description: 'GitHub repository name'
    required: false
    default: ${{ github.repository }}  # Set the default to the current repo name
  verbose:
    description: 'Enable verbose output'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Run PowerShell script
      shell: pwsh
      run: |
        $VerboseFlag = if (${{ inputs.verbose }}) { '-Verbose' } else { '' }
        & $env:GITHUB_ACTION_PATH\\update-readme.ps1 -ProjectName '${{ inputs.project_name }}' -RootPath '${{ github.workspace }}' -GithubOwner '${{ inputs.github_owner }}' -GithubRepo '${{ inputs.github_repo }}' $env:VERBOSE

    - name: Commit and push updated README.md
      shell: bash
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update README with badges"
        git push
